site_name: Network Policy API
repo_url: https://github.com/kubernetes-sigs/network-policy-api
repo_name: kubernetes-sigs/network-policy-api
site_dir: site
docs_dir: site-src
hooks:
- hack/mkdocs-copy-npeps.py
watch:
- npeps
theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  logo: images/k8s-favicon.png
  favicon: images/k8s-favicon.png
  features:
    - search.highlight
    - navigation.tabs
    - navigation.top
edit_uri: edit/master/site-src/
plugins:
  - search
  - awesome-pages
  - macros:
      #include_dir: examples
      j2_line_comment_prefix: "#$"
  - blog:
      # NOTE: configuration options can be found at
      # https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/
      blog_dir: blog
      blog_toc: true
      #post_excerpt: required
      post_excerpt_max_authors: 2
markdown_extensions:
  - admonition
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: site-src
      check_paths: true
  - toc:
      permalink: true
nav:
  - Introduction: index.md
  - Overview:
    - User Stories: user-stories.md
    - Resources: api-overview.md
    - Versioning: versioning.md
    - Conformance: conformance.md
    - Implementations: implementations.md
  - Guides:
    - Getting started: getting-started.md
  - Reference:
    - Examples: reference/examples.md
    - API Reference: reference/spec.md
    - Enhancement Proposals:
      - Overview: enhancements.md
      - Template: npeps/npep-95.md
      - Provisional:
        - npeps/npep-122.md
        - npeps/npep-133.md
      - Implementable:
        - npeps/npep-137-conformance-profiles.md
        - npeps/npep-126-egress-traffic-control.md
        # - Experimental:
        # - Standard:
        # - Declined:
  - Blog:
    - blog/index.md
