# Netlify build instructions
[build]
    command = "make docs"
    publish = "site"
[build.environment]
    PYTHON_VERSION = "3.8"
    GO_VERSION = "1.21.4"

# Standard Netlify redirects
[[redirects]]
    from = "https://master--kubernetes-sigs-network-policy-api.netlify.app/*"
    to = "https://master.network-policy-api.sigs.k8s.io/:splat"
    status = 301
    force = true

# HTTP-to-HTTPS rules
[[redirects]]
    from = "http://master.network-policy-api.sigs.k8s.io/*"
    to = "https://master.network-policy-api.sigs.k8s.io/:splat"
    status = 301
    force = true

[[redirects]]
    from = "http://master--kubernetes-sigs-network-policy-api.netlify.app/*"
    to = "http://master.network-policy-api.sigs.k8s.io/:splat"
    status = 301
    force = true
    
